steps:
  # Build the container image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SITE_URL=https://thecryptob.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_GA_MEASUREMENT_ID=G-3PW6GGDX6F'
      - '--build-arg'
      - 'NEXT_PUBLIC_BTC_WALLET=bc1qgswmplz72qqxpp6sffux07nfwh32v8hqhzrwwa'
      - '--build-arg'
      - 'NEXT_PUBLIC_ETH_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296'
      - '--build-arg'
      - 'NEXT_PUBLIC_BASE_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296'
      - '--build-arg'
      - 'NEXT_PUBLIC_SOL_WALLET=FQDn463DWY1WZNFsR87Anqmh49ViE4mYbFfpxf9h7B7w'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUI_WALLET=0x15b94dc1970248cb17882364ad6c0e93c6aa79c0d8bb3279fbb28336e11029c3'
      - '--build-arg'
      - 'NEXT_PUBLIC_METAMASK_WALLET=0xFE1C6127C6C8d1aCDA1e883e6A146CDd075F6491'
      - '--build-arg'
      - 'NEXT_PUBLIC_BMC_URL=https://buymeacoffee.com/thecryptob'
      - '--build-arg'
      - 'NEXT_PUBLIC_TWITTER_URL=https://x.com/TheCrypto_B'
      - '--build-arg'
      - 'NEXT_PUBLIC_YOUTUBE_URL=https://www.youtube.com/@Crypto_B'
      - '--build-arg'
      - 'NEXT_PUBLIC_CMC_URL=https://coinmarketcap.com/community/profile/TheCrypto_B/'
      - '--build-arg'
      - 'NEXT_PUBLIC_BINANCE_WS_URL=wss://stream.binance.com:9443/ws'
      - '--build-arg'
      - 'NEXT_PUBLIC_COINGECKO_API_URL=https://api.coingecko.com/api/v3'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=https://ikfnwmzawdzdhupkaxcj.supabase.co'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZm53bXphd2R6ZGh1cGtheGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3Mzg3ODMsImV4cCI6MjA3NjMxNDc4M30.Wc2H9pV4OjuqBIEydG-wvpK_26kTDKL3W1bVSOpLvDw'
      - '--build-arg'
      - 'B_DASHBOARD_PASSWORD=1980_Casquinha#'
      - '-t'
      - 'gcr.io/$PROJECT_ID/thecryptob:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/thecryptob:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/thecryptob:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/thecryptob:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'thecryptob'
      - '--image'
      - 'gcr.io/$PROJECT_ID/thecryptob:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SITE_URL=https://thecryptob.com,NEXT_PUBLIC_GA_MEASUREMENT_ID=G-3PW6GGDX6F,NEXT_PUBLIC_BTC_WALLET=bc1qgswmplz72qqxpp6sffux07nfwh32v8hqhzrwwa,NEXT_PUBLIC_ETH_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296,NEXT_PUBLIC_BASE_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296,NEXT_PUBLIC_SOL_WALLET=FQDn463DWY1WZNFsR87Anqmh49ViE4mYbFfpxf9h7B7w,NEXT_PUBLIC_SUI_WALLET=0x15b94dc1970248cb17882364ad6c0e93c6aa79c0d8bb3279fbb28336e11029c3,NEXT_PUBLIC_METAMASK_WALLET=0xFE1C6127C6C8d1aCDA1e883e6A146CDd075F6491,NEXT_PUBLIC_BMC_URL=https://buymeacoffee.com/thecryptob,NEXT_PUBLIC_TWITTER_URL=https://x.com/TheCrypto_B,NEXT_PUBLIC_YOUTUBE_URL=https://www.youtube.com/@Crypto_B,NEXT_PUBLIC_CMC_URL=https://coinmarketcap.com/community/profile/TheCrypto_B/,NEXT_PUBLIC_BINANCE_WS_URL=wss://stream.binance.com:9443/ws,NEXT_PUBLIC_COINGECKO_API_URL=https://api.coingecko.com/api/v3,NEXT_PUBLIC_SUPABASE_URL=https://ikfnwmzawdzdhupkaxcj.supabase.co,NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZm53bXphd2R6ZGh1cGtheGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3Mzg3ODMsImV4cCI6MjA3NjMxNDc4M30.Wc2H9pV4OjuqBIEydG-wvpK_26kTDKL3W1bVSOpLvDw,B_DASHBOARD_PASSWORD=1980_Casquinha#'
      - '--port'
      - '8080'

images:
  - 'gcr.io/$PROJECT_ID/thecryptob:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/thecryptob:latest'

options:
  logging: CLOUD_LOGGING_ONLY
