name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: celtic-music-473110-a6
  SERVICE_NAME: thecryptob
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image with build args
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_SITE_URL=https://thecryptob.com \
            --build-arg NEXT_PUBLIC_GA_MEASUREMENT_ID=G-3PW6GGDX6F \
            --build-arg NEXT_PUBLIC_BTC_WALLET=bc1qgswmplz72qqxpp6sffux07nfwh32v8hqhzrwwa \
            --build-arg NEXT_PUBLIC_ETH_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296 \
            --build-arg NEXT_PUBLIC_BASE_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296 \
            --build-arg NEXT_PUBLIC_SOL_WALLET=FQDn463DWY1WZNFsR87Anqmh49ViE4mYbFfpxf9h7B7w \
            --build-arg NEXT_PUBLIC_SUI_WALLET=0x15b94dc1970248cb17882364ad6c0e93c6aa79c0d8bb3279fbb28336e11029c3 \
            --build-arg NEXT_PUBLIC_METAMASK_WALLET=0xFE1C6127C6C8d1aCDA1e883e6A146CDd075F6491 \
            --build-arg NEXT_PUBLIC_BMC_URL=https://buymeacoffee.com/thecryptob \
            --build-arg NEXT_PUBLIC_TWITTER_URL=https://x.com/TheCrypto_B \
            --build-arg NEXT_PUBLIC_YOUTUBE_URL=https://www.youtube.com/@Crypto_B \
            --build-arg NEXT_PUBLIC_CMC_URL=https://coinmarketcap.com/community/profile/TheCrypto_B/ \
            --build-arg NEXT_PUBLIC_BINANCE_WS_URL=wss://stream.binance.com:9443/ws \
            --build-arg NEXT_PUBLIC_COINGECKO_API_URL=https://api.coingecko.com/api/v3 \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "NEXT_PUBLIC_SITE_URL=https://thecryptob.com,NEXT_PUBLIC_GA_MEASUREMENT_ID=G-3PW6GGDX6F,NEXT_PUBLIC_BTC_WALLET=bc1qgswmplz72qqxpp6sffux07nfwh32v8hqhzrwwa,NEXT_PUBLIC_ETH_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296,NEXT_PUBLIC_BASE_WALLET=0x4ef74D71FBF937BC49E678c2C3FAF124f4790296,NEXT_PUBLIC_SOL_WALLET=FQDn463DWY1WZNFsR87Anqmh49ViE4mYbFfpxf9h7B7w,NEXT_PUBLIC_SUI_WALLET=0x15b94dc1970248cb17882364ad6c0e93c6aa79c0d8bb3279fbb28336e11029c3,NEXT_PUBLIC_METAMASK_WALLET=0xFE1C6127C6C8d1aCDA1e883e6A146CDd075F6491,NEXT_PUBLIC_BMC_URL=https://buymeacoffee.com/thecryptob,NEXT_PUBLIC_TWITTER_URL=https://x.com/TheCrypto_B,NEXT_PUBLIC_YOUTUBE_URL=https://www.youtube.com/@Crypto_B,NEXT_PUBLIC_CMC_URL=https://coinmarketcap.com/community/profile/TheCrypto_B/,NEXT_PUBLIC_BINANCE_WS_URL=wss://stream.binance.com:9443/ws,NEXT_PUBLIC_COINGECKO_API_URL=https://api.coingecko.com/api/v3" \
            --port 8080

      - name: Show service URL
        run: |
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format 'value(status.url)'
